# Generated by Django 4.2 on 2023-12-18 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_decription_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='prduct',
        ),
        migrations.AddField(
            model_name='file',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='products.product', verbose_name='product'),
            preserve_default=False,
        ),
    ]
