# Generated by Django 4.2 on 2023-12-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_file_prduct_file_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'audio'), (2, 'video'), (3, 'text')], default=2, verbose_name='file type'),
            preserve_default=False,
        ),
    ]
